- group: {name: future, enabled: true}
- group: {name: generalise, enabled: true}
- functions:
  - {name: undefined, within: []}
- ignore: {name: Use pure}
- ignore: {name: Use print}
- ignore: {name: Use null}
- ignore: {name: Use notElem}
- ignore: {name: Use unless}
- ignore: {name: Use fmap}
# !! 0 is good in tests for uniformity with other !! n
- ignore: {name: Use head}
